'use strict';

const fs = require('fs');
const os = require('os');
const path = require('path');
const { execFileSync } = require('child_process');
const { gitRoot } = require('./utils');
const { name: PACKAGE_NAME } = require('../package.json');

const MARKER_START = '# >>> pushguard >>>';
const MARKER_END = '# <<< pushguard <<<';

function hookBody({ autoFix = false, hookName = 'pre-push', paranoid = false } = {}) {
  const paranoidFlag = paranoid ? ' --paranoid' : '';

  if (hookName === 'pre-commit') {
    const scanCmd = autoFix ? `pushguard fix --staged${paranoidFlag} --yes` : `pushguard scan --staged${paranoidFlag}`;
    const npxCmd = autoFix ? `fix --staged${paranoidFlag} --yes` : `scan --staged${paranoidFlag}`;
    return `${MARKER_START}
# PushGuard: stop leaked tokens before they reach GitHub.
# Generated by: pushguard install --pre-commit${autoFix ? ' --auto-fix' : ''}${paranoid ? ' --paranoid' : ''}
if command -v pushguard >/dev/null 2>&1; then
  ${scanCmd}
  status=$?
elif command -v npx >/dev/null 2>&1; then
  npx --yes ${PACKAGE_NAME} ${npxCmd}
  status=$?
else
  echo "pushguard: command not found. Install with: npm i -g ${PACKAGE_NAME}"
  status=1
fi

if [ "$status" -ne 0 ]; then
  echo ""
  echo "🛑 pushguard blocked this commit. Fix the issue, git add changes, then retry."
  exit "$status"
fi
${MARKER_END}`;
  }

  // Git passes the exact refs being pushed to pre-push on stdin:
  // <local ref> <local sha> <remote ref> <remote sha>
  // We capture it once and feed it into pushguard so it scans only outgoing commit files.
  const scanCmd = `scan --pre-push${paranoidFlag}`;
  const fixCmd = `fix --push-files${paranoidFlag} --yes`;
  return `${MARKER_START}
# PushGuard: stop leaked tokens before they reach GitHub.
# Generated by: pushguard install${autoFix ? ' --auto-fix' : ''}${paranoid ? ' --paranoid' : ''}
git_pushguard_push_input=$(cat)

run_git_pushguard() {
  if command -v pushguard >/dev/null 2>&1; then
    printf '%s\n' "$git_pushguard_push_input" | pushguard "$@"
    return $?
  elif command -v npx >/dev/null 2>&1; then
    printf '%s\n' "$git_pushguard_push_input" | npx --yes ${PACKAGE_NAME} "$@"
    return $?
  else
    echo "pushguard: command not found. Install with: npm i -g ${PACKAGE_NAME}"
    return 1
  fi
}

run_git_pushguard ${scanCmd}
status=$?

if [ "$status" -ne 0 ] && [ "${autoFix ? '1' : '0'}" = "1" ]; then
  echo ""
  echo "🛠️  pushguard: trying safe working-tree fixes for pushed files..."
  run_git_pushguard ${fixCmd}
  echo ""
  echo "Review the changes, commit/amend them, then push again."
  status=1
fi

if [ "$status" -ne 0 ]; then
  echo ""
  echo "🛑 pushguard blocked this push. It scanned only files in the outgoing commits."
  exit "$status"
fi

# If global hooksPath is active, Git skips .git/hooks/pre-push.
# Chain an existing repo-local pre-push hook when it exists and is not PushGuard-managed.
repo_git_dir=$(git rev-parse --git-dir 2>/dev/null || true)
if [ -n "$repo_git_dir" ] && [ -x "$repo_git_dir/hooks/pre-push" ]; then
  if ! grep -q "${MARKER_START}" "$repo_git_dir/hooks/pre-push" 2>/dev/null; then
    printf '%s\n' "$git_pushguard_push_input" | "$repo_git_dir/hooks/pre-push" "$@"
    local_hook_status=$?
    if [ "$local_hook_status" -ne 0 ]; then
      exit "$local_hook_status"
    fi
  fi
fi
${MARKER_END}`;
}

function ensureHookFile(hookPath, body) {
  let existing = '';
  if (fs.existsSync(hookPath)) existing = fs.readFileSync(hookPath, 'utf8');
  let next;
  if (!existing.trim()) {
    next = `#!/usr/bin/env sh\n\n${body}\n`;
  } else if (existing.includes(MARKER_START) && existing.includes(MARKER_END)) {
    const re = new RegExp(`${escapeRegExp(MARKER_START)}[\\s\\S]*?${escapeRegExp(MARKER_END)}`);
    next = existing.replace(re, body);
  } else {
    next = `${existing.replace(/\s*$/, '')}\n\n${body}\n`;
  }
  fs.mkdirSync(path.dirname(hookPath), { recursive: true });
  fs.writeFileSync(hookPath, next, { mode: 0o755 });
  try { fs.chmodSync(hookPath, 0o755); } catch (_) {}
}

function escapeRegExp(s) {
  return String(s).replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

function hookNamesFor(options = {}) {
  if (options.both) return ['pre-commit', 'pre-push'];
  return [options.preCommit ? 'pre-commit' : 'pre-push'];
}

function installLocal(options = {}) {
  const root = gitRoot();
  if (!root) throw new Error('Not inside a Git repository. Run git init first.');
  const hookNames = hookNamesFor(options);
  const installed = [];
  for (const hookName of hookNames) {
    const hookPath = path.join(root, '.git', 'hooks', hookName);
    ensureHookFile(hookPath, hookBody({ autoFix: options.autoFix, hookName, paranoid: options.paranoid }));
    installed.push({ hookName, hookPath });
  }
  return { scope: 'local', root, hookName: hookNames.join(', '), hookPath: installed.map(x => x.hookPath).join(', '), installed };
}

function installGlobal(options = {}) {
  const hooksPath = path.join(os.homedir(), '.pushguard', 'hooks');
  const hookNames = hookNamesFor(options);
  fs.mkdirSync(hooksPath, { recursive: true });
  const installed = [];
  for (const hookName of hookNames) {
    const hookPath = path.join(hooksPath, hookName);
    ensureHookFile(hookPath, hookBody({ autoFix: options.autoFix, hookName, paranoid: options.paranoid }));
    installed.push({ hookName, hookPath });
  }
  execFileSync('git', ['config', '--global', 'core.hooksPath', hooksPath], { stdio: 'ignore' });
  return { scope: 'global', hooksPath, hookName: hookNames.join(', '), hookPath: installed.map(x => x.hookPath).join(', '), installed };
}

function removeMarkedBlock(hookPath) {
  if (!fs.existsSync(hookPath)) return false;
  const existing = fs.readFileSync(hookPath, 'utf8');
  if (!existing.includes(MARKER_START)) return false;
  const re = new RegExp(`\n?${escapeRegExp(MARKER_START)}[\\s\\S]*?${escapeRegExp(MARKER_END)}\n?`, 'g');
  const next = existing.replace(re, '\n').replace(/\n{3,}/g, '\n\n');
  fs.writeFileSync(hookPath, next, { mode: 0o755 });
  return true;
}

function uninstallLocal(options = {}) {
  const root = gitRoot();
  if (!root) throw new Error('Not inside a Git repository.');
  const removed = [];
  for (const hookName of ['pre-push', 'pre-commit']) {
    const hookPath = path.join(root, '.git', 'hooks', hookName);
    if (removeMarkedBlock(hookPath)) removed.push(hookName);
  }
  return { scope: 'local', root, removed };
}

function globalHooksPath() {
  return path.join(os.homedir(), '.pushguard', 'hooks');
}

function currentGlobalHooksPath() {
  try {
    return execFileSync('git', ['config', '--global', '--get', 'core.hooksPath'], { encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] }).trim();
  } catch (_) {
    return '';
  }
}

function statusGlobal() {
  const hooksPath = globalHooksPath();
  const configuredHooksPath = currentGlobalHooksPath();
  const prePushPath = path.join(hooksPath, 'pre-push');
  const preCommitPath = path.join(hooksPath, 'pre-commit');
  const prePushExists = fs.existsSync(prePushPath);
  const preCommitExists = fs.existsSync(preCommitPath);
  const active = configuredHooksPath === hooksPath && prePushExists;
  return {
    active,
    hooksPath,
    configuredHooksPath,
    prePushPath,
    prePushExists,
    preCommitPath,
    preCommitExists
  };
}

function uninstallGlobal() {
  const hooksPath = globalHooksPath();
  const removed = [];
  for (const hookName of ['pre-push', 'pre-commit']) {
    const hookPath = path.join(hooksPath, hookName);
    if (removeMarkedBlock(hookPath)) removed.push(hookName);
  }
  const configuredHooksPath = currentGlobalHooksPath();
  let configUnset = false;
  if (configuredHooksPath === hooksPath) {
    try {
      execFileSync('git', ['config', '--global', '--unset', 'core.hooksPath'], { stdio: 'ignore' });
      configUnset = true;
    } catch (_) {}
  }
  return { scope: 'global', hooksPath, removed, configUnset };
}

module.exports = {
  installLocal,
  installGlobal,
  uninstallLocal,
  uninstallGlobal,
  statusGlobal,
  hookBody,
  MARKER_START,
  MARKER_END
};
