'use strict';

// Provider catalogue used by the provider-aware generic scanner.
// It does not mean every provider has a public fixed token regex. Many providers
// use random keys, so PushGuard combines this provider intelligence with
// secret-keyword + entropy checks. The expanded fingerprint count is >1000.

const SECRET_SUFFIXES = ["api_key", "apikey", "api_token", "token", "access_token", "secret", "client_secret", "app_secret", "webhook", "webhook_url", "private_key", "service_key", "service_role", "auth_token", "refresh_token", "bearer_token", "dsn", "connection_string", "password"];
const ALLOWED_SHORT_ALIASES = new Set(["aws", "gcp", "cf", "do", "hf", "gh", "gl", "dd", "tg", "wa", "ig", "yt", "op", "ld", "mx", "r2", "s3", "b2", "ai", "x"]);

const PROVIDERS = [
  { id: 'aws', title: 'AWS', aliases: ["aws", "AWS", "amazon web services", "amazonaws", "s3", "ec2", "iam", "sts"] },
  { id: 'azure', title: 'Microsoft Azure', aliases: ["azure", "Microsoft Azure", "microsoft azure", "azuread", "aad"] },
  { id: 'gcp', title: 'Google Cloud', aliases: ["gcp", "Google Cloud", "google cloud", "googlecloud", "gcloud", "google"] },
  { id: 'cloudflare', title: 'Cloudflare', aliases: ["cloudflare", "Cloudflare", "cf", "cloudflare_api", "cloudflareapi", "r2", "workers"] },
  { id: 'vercel', title: 'Vercel', aliases: ["vercel", "Vercel", "vercel_token"] },
  { id: 'netlify', title: 'Netlify', aliases: ["netlify", "Netlify"] },
  { id: 'render', title: 'Render', aliases: ["render", "Render"] },
  { id: 'railway', title: 'Railway', aliases: ["railway", "Railway"] },
  { id: 'fly', title: 'Fly.io', aliases: ["fly", "Fly.io", "flyio"] },
  { id: 'heroku', title: 'Heroku', aliases: ["heroku", "Heroku"] },
  { id: 'digitalocean', title: 'DigitalOcean', aliases: ["digitalocean", "DigitalOcean", "digital ocean", "do"] },
  { id: 'linode', title: 'Linode', aliases: ["linode", "Linode", "akamai cloud", "akamai"] },
  { id: 'vultr', title: 'Vultr', aliases: ["vultr", "Vultr"] },
  { id: 'scaleway', title: 'Scaleway', aliases: ["scaleway", "Scaleway"] },
  { id: 'oraclecloud', title: 'Oracle Cloud', aliases: ["oraclecloud", "Oracle Cloud", "oracle cloud", "oci"] },
  { id: 'ibmcloud', title: 'IBM Cloud', aliases: ["ibmcloud", "IBM Cloud", "ibm cloud", "bluemix"] },
  { id: 'alibaba', title: 'Alibaba Cloud', aliases: ["alibaba", "Alibaba Cloud", "aliyun", "alibaba cloud"] },
  { id: 'tencent', title: 'Tencent Cloud', aliases: ["tencent", "Tencent Cloud", "tencent cloud"] },
  { id: 'hetzner', title: 'Hetzner', aliases: ["hetzner", "Hetzner"] },
  { id: 'ovh', title: 'OVHcloud', aliases: ["ovh", "OVHcloud", "ovhcloud"] },
  { id: 'upcloud', title: 'UpCloud', aliases: ["upcloud", "UpCloud"] },
  { id: 'backblaze', title: 'Backblaze', aliases: ["backblaze", "Backblaze", "b2"] },
  { id: 'wasabi', title: 'Wasabi', aliases: ["wasabi", "Wasabi"] },
  { id: 'minio', title: 'MinIO', aliases: ["minio", "MinIO"] },
  { id: 'supabase', title: 'Supabase', aliases: ["supabase", "Supabase"] },
  { id: 'firebase', title: 'Firebase', aliases: ["firebase", "Firebase", "fcm", "firestore", "crashlytics"] },
  { id: 'appwrite', title: 'Appwrite', aliases: ["appwrite", "Appwrite"] },
  { id: 'pocketbase', title: 'PocketBase', aliases: ["pocketbase", "PocketBase"] },
  { id: 'hasura', title: 'Hasura', aliases: ["hasura", "Hasura"] },
  { id: 'neon', title: 'Neon', aliases: ["neon", "Neon", "neonpostgres", "neon_db"] },
  { id: 'planetscale', title: 'PlanetScale', aliases: ["planetscale", "PlanetScale", "planet scale"] },
  { id: 'mongodb', title: 'MongoDB', aliases: ["mongodb", "MongoDB", "mongo", "atlas", "mongodb atlas"] },
  { id: 'postgres', title: 'Postgres', aliases: ["postgres", "Postgres", "postgresql"] },
  { id: 'mysql', title: 'MySQL', aliases: ["mysql", "MySQL", "mariadb"] },
  { id: 'redis', title: 'Redis', aliases: ["redis", "Redis"] },
  { id: 'upstash', title: 'Upstash', aliases: ["upstash", "Upstash"] },
  { id: 'qdrant', title: 'Qdrant', aliases: ["qdrant", "Qdrant"] },
  { id: 'pinecone', title: 'Pinecone', aliases: ["pinecone", "Pinecone"] },
  { id: 'weaviate', title: 'Weaviate', aliases: ["weaviate", "Weaviate"] },
  { id: 'chroma', title: 'Chroma', aliases: ["chroma", "Chroma", "chromadb"] },
  { id: 'milvus', title: 'Milvus', aliases: ["milvus", "Milvus", "zilliz"] },
  { id: 'elastic', title: 'Elastic', aliases: ["elastic", "Elastic", "elasticsearch", "elasticcloud"] },
  { id: 'opensearch', title: 'OpenSearch', aliases: ["opensearch", "OpenSearch"] },
  { id: 'algolia', title: 'Algolia', aliases: ["algolia", "Algolia"] },
  { id: 'meilisearch', title: 'Meilisearch', aliases: ["meilisearch", "Meilisearch", "meili"] },
  { id: 'typesense', title: 'Typesense', aliases: ["typesense", "Typesense"] },
  { id: 'datadog', title: 'Datadog', aliases: ["datadog", "Datadog", "dd"] },
  { id: 'newrelic', title: 'New Relic', aliases: ["newrelic", "New Relic", "new relic"] },
  { id: 'sentry', title: 'Sentry', aliases: ["sentry", "Sentry"] },
  { id: 'rollbar', title: 'Rollbar', aliases: ["rollbar", "Rollbar"] },
  { id: 'bugsnag', title: 'Bugsnag', aliases: ["bugsnag", "Bugsnag"] },
  { id: 'honeybadger', title: 'Honeybadger', aliases: ["honeybadger", "Honeybadger"] },
  { id: 'betterstack', title: 'Better Stack', aliases: ["betterstack", "Better Stack", "logtail"] },
  { id: 'logflare', title: 'Logflare', aliases: ["logflare", "Logflare"] },
  { id: 'grafana', title: 'Grafana', aliases: ["grafana", "Grafana"] },
  { id: 'prometheus', title: 'Prometheus', aliases: ["prometheus", "Prometheus"] },
  { id: 'loki', title: 'Grafana Loki', aliases: ["loki", "Grafana Loki"] },
  { id: 'splunk', title: 'Splunk', aliases: ["splunk", "Splunk"] },
  { id: 'sumologic', title: 'Sumo Logic', aliases: ["sumologic", "Sumo Logic", "sumo logic"] },
  { id: 'pagerduty', title: 'PagerDuty', aliases: ["pagerduty", "PagerDuty"] },
  { id: 'opsgenie', title: 'Opsgenie', aliases: ["opsgenie", "Opsgenie"] },
  { id: 'victorops', title: 'VictorOps', aliases: ["victorops", "VictorOps", "splunk on-call"] },
  { id: 'statuspage', title: 'Statuspage', aliases: ["statuspage", "Statuspage"] },
  { id: 'twilio', title: 'Twilio', aliases: ["twilio", "Twilio"] },
  { id: 'sendgrid', title: 'SendGrid', aliases: ["sendgrid", "SendGrid"] },
  { id: 'mailgun', title: 'Mailgun', aliases: ["mailgun", "Mailgun"] },
  { id: 'mailchimp', title: 'Mailchimp', aliases: ["mailchimp", "Mailchimp", "mandrill"] },
  { id: 'postmark', title: 'Postmark', aliases: ["postmark", "Postmark"] },
  { id: 'resend', title: 'Resend', aliases: ["resend", "Resend"] },
  { id: 'brevo', title: 'Brevo', aliases: ["brevo", "Brevo", "sendinblue"] },
  { id: 'ses', title: 'Amazon SES', aliases: ["ses", "Amazon SES", "amazon ses", "aws ses"] },
  { id: 'smtp2go', title: 'SMTP2GO', aliases: ["smtp2go", "SMTP2GO"] },
  { id: 'sparkpost', title: 'SparkPost', aliases: ["sparkpost", "SparkPost"] },
  { id: 'plivo', title: 'Plivo', aliases: ["plivo", "Plivo"] },
  { id: 'vonage', title: 'Vonage', aliases: ["vonage", "Vonage", "nexmo"] },
  { id: 'messagebird', title: 'MessageBird', aliases: ["messagebird", "MessageBird", "bird"] },
  { id: 'telegram', title: 'Telegram', aliases: ["telegram", "Telegram", "tg", "botfather"] },
  { id: 'discord', title: 'Discord', aliases: ["discord", "Discord"] },
  { id: 'slack', title: 'Slack', aliases: ["slack", "Slack"] },
  { id: 'mattermost', title: 'Mattermost', aliases: ["mattermost", "Mattermost"] },
  { id: 'msteams', title: 'Microsoft Teams', aliases: ["msteams", "Microsoft Teams", "teams", "microsoft teams"] },
  { id: 'line', title: 'LINE', aliases: ["line", "LINE", "linebot"] },
  { id: 'whatsapp', title: 'WhatsApp', aliases: ["whatsapp", "WhatsApp", "wa"] },
  { id: 'facebook', title: 'Facebook', aliases: ["facebook", "Facebook", "fb", "meta facebook"] },
  { id: 'instagram', title: 'Instagram', aliases: ["instagram", "Instagram", "ig"] },
  { id: 'twitter', title: 'X/Twitter', aliases: ["twitter", "X/Twitter", "x_api", "xapi", "x-twitter"] },
  { id: 'linkedin', title: 'LinkedIn', aliases: ["linkedin", "LinkedIn"] },
  { id: 'reddit', title: 'Reddit', aliases: ["reddit", "Reddit"] },
  { id: 'twitch', title: 'Twitch', aliases: ["twitch", "Twitch"] },
  { id: 'youtube', title: 'YouTube', aliases: ["youtube", "YouTube", "yt"] },
  { id: 'tiktok', title: 'TikTok', aliases: ["tiktok", "TikTok"] },
  { id: 'pinterest', title: 'Pinterest', aliases: ["pinterest", "Pinterest"] },
  { id: 'bluesky', title: 'Bluesky', aliases: ["bluesky", "Bluesky", "bsky"] },
  { id: 'mastodon', title: 'Mastodon', aliases: ["mastodon", "Mastodon"] },
  { id: 'openai', title: 'OpenAI', aliases: ["openai", "OpenAI", "chatgpt"] },
  { id: 'anthropic', title: 'Anthropic', aliases: ["anthropic", "Anthropic", "claude"] },
  { id: 'gemini', title: 'Google Gemini', aliases: ["gemini", "Google Gemini", "google ai", "google generative ai"] },
  { id: 'deepseek', title: 'DeepSeek', aliases: ["deepseek", "DeepSeek"] },
  { id: 'groq', title: 'Groq', aliases: ["groq", "Groq"] },
  { id: 'mistral', title: 'Mistral', aliases: ["mistral", "Mistral", "mistralai"] },
  { id: 'cohere', title: 'Cohere', aliases: ["cohere", "Cohere"] },
  { id: 'perplexity', title: 'Perplexity', aliases: ["perplexity", "Perplexity", "pplx"] },
  { id: 'openrouter', title: 'OpenRouter', aliases: ["openrouter", "OpenRouter", "open router"] },
  { id: 'huggingface', title: 'Hugging Face', aliases: ["huggingface", "Hugging Face", "hugging face", "hf"] },
  { id: 'replicate', title: 'Replicate', aliases: ["replicate", "Replicate"] },
  { id: 'stability', title: 'Stability AI', aliases: ["stability", "Stability AI", "stabilityai", "stable diffusion"] },
  { id: 'elevenlabs', title: 'ElevenLabs', aliases: ["elevenlabs", "ElevenLabs", "eleven labs"] },
  { id: 'assemblyai', title: 'AssemblyAI', aliases: ["assemblyai", "AssemblyAI", "assembly ai"] },
  { id: 'deepgram', title: 'Deepgram', aliases: ["deepgram", "Deepgram"] },
  { id: 'revai', title: 'Rev.ai', aliases: ["revai", "Rev.ai", "rev ai"] },
  { id: 'nvidia', title: 'NVIDIA', aliases: ["nvidia", "NVIDIA", "nim", "nvapi"] },
  { id: 'cerebras', title: 'Cerebras', aliases: ["cerebras", "Cerebras"] },
  { id: 'together', title: 'Together AI', aliases: ["together", "Together AI", "togetherai", "together ai"] },
  { id: 'fireworks', title: 'Fireworks AI', aliases: ["fireworks", "Fireworks AI", "fireworksai"] },
  { id: 'voyage', title: 'Voyage AI', aliases: ["voyage", "Voyage AI", "voyageai"] },
  { id: 'jina', title: 'Jina AI', aliases: ["jina", "Jina AI", "jinaai"] },
  { id: 'langsmith', title: 'LangSmith', aliases: ["langsmith", "LangSmith"] },
  { id: 'langchain', title: 'LangChain', aliases: ["langchain", "LangChain"] },
  { id: 'langfuse', title: 'Langfuse', aliases: ["langfuse", "Langfuse"] },
  { id: 'helicone', title: 'Helicone', aliases: ["helicone", "Helicone"] },
  { id: 'wandb', title: 'Weights & Biases', aliases: ["wandb", "Weights & Biases", "weightsbiases", "weights and biases"] },
  { id: 'modal', title: 'Modal', aliases: ["modal", "Modal"] },
  { id: 'runpod', title: 'RunPod', aliases: ["runpod", "RunPod"] },
  { id: 'baseten', title: 'Baseten', aliases: ["baseten", "Baseten"] },
  { id: 'beam', title: 'Beam Cloud', aliases: ["beam", "Beam Cloud", "beam cloud"] },
  { id: 'banana', title: 'Banana.dev', aliases: ["banana", "Banana.dev", "banana dev"] },
  { id: 'stripe', title: 'Stripe', aliases: ["stripe", "Stripe"] },
  { id: 'paypal', title: 'PayPal', aliases: ["paypal", "PayPal"] },
  { id: 'razorpay', title: 'Razorpay', aliases: ["razorpay", "Razorpay"] },
  { id: 'square', title: 'Square', aliases: ["square", "Square"] },
  { id: 'adyen', title: 'Adyen', aliases: ["adyen", "Adyen"] },
  { id: 'mollie', title: 'Mollie', aliases: ["mollie", "Mollie"] },
  { id: 'paddle', title: 'Paddle', aliases: ["paddle", "Paddle"] },
  { id: 'lemonsqueezy', title: 'Lemon Squeezy', aliases: ["lemonsqueezy", "Lemon Squeezy", "lemon squeezy"] },
  { id: 'chargebee', title: 'Chargebee', aliases: ["chargebee", "Chargebee"] },
  { id: 'recurly', title: 'Recurly', aliases: ["recurly", "Recurly"] },
  { id: 'braintree', title: 'Braintree', aliases: ["braintree", "Braintree"] },
  { id: 'coinbase', title: 'Coinbase', aliases: ["coinbase", "Coinbase"] },
  { id: 'bitpay', title: 'BitPay', aliases: ["bitpay", "BitPay"] },
  { id: 'paytm', title: 'Paytm', aliases: ["paytm", "Paytm"] },
  { id: 'phonepe', title: 'PhonePe', aliases: ["phonepe", "PhonePe"] },
  { id: 'cashfree', title: 'Cashfree', aliases: ["cashfree", "Cashfree"] },
  { id: 'instamojo', title: 'Instamojo', aliases: ["instamojo", "Instamojo"] },
  { id: 'midtrans', title: 'Midtrans', aliases: ["midtrans", "Midtrans"] },
  { id: 'xendit', title: 'Xendit', aliases: ["xendit", "Xendit"] },
  { id: 'dlocal', title: 'dLocal', aliases: ["dlocal", "dLocal", "d local"] },
  { id: 'wise', title: 'Wise', aliases: ["wise", "Wise", "transferwise"] },
  { id: 'plaid', title: 'Plaid', aliases: ["plaid", "Plaid"] },
  { id: 'yodlee', title: 'Yodlee', aliases: ["yodlee", "Yodlee"] },
  { id: 'finicity', title: 'Finicity', aliases: ["finicity", "Finicity"] },
  { id: 'mx', title: 'MX', aliases: ["mx", "MX"] },
  { id: 'github', title: 'GitHub', aliases: ["github", "GitHub", "gh"] },
  { id: 'gitlab', title: 'GitLab', aliases: ["gitlab", "GitLab", "gl"] },
  { id: 'bitbucket', title: 'Bitbucket', aliases: ["bitbucket", "Bitbucket"] },
  { id: 'circleci', title: 'CircleCI', aliases: ["circleci", "CircleCI", "circle ci"] },
  { id: 'travisci', title: 'Travis CI', aliases: ["travisci", "Travis CI", "travis", "travis ci"] },
  { id: 'githubactions', title: 'GitHub Actions', aliases: ["githubactions", "GitHub Actions", "github actions", "gha", "actions"] },
  { id: 'jenkins', title: 'Jenkins', aliases: ["jenkins", "Jenkins"] },
  { id: 'buildkite', title: 'Buildkite', aliases: ["buildkite", "Buildkite"] },
  { id: 'codeship', title: 'Codeship', aliases: ["codeship", "Codeship"] },
  { id: 'drone', title: 'Drone CI', aliases: ["drone", "Drone CI", "droneci"] },
  { id: 'semaphore', title: 'Semaphore CI', aliases: ["semaphore", "Semaphore CI", "semaphoreci"] },
  { id: 'teamcity', title: 'TeamCity', aliases: ["teamcity", "TeamCity"] },
  { id: 'bamboo', title: 'Bamboo', aliases: ["bamboo", "Bamboo"] },
  { id: 'sonarqube', title: 'SonarQube', aliases: ["sonarqube", "SonarQube", "sonar"] },
  { id: 'sonarcloud', title: 'SonarCloud', aliases: ["sonarcloud", "SonarCloud"] },
  { id: 'snyk', title: 'Snyk', aliases: ["snyk", "Snyk"] },
  { id: 'socket', title: 'Socket.dev', aliases: ["socket", "Socket.dev", "socketdev"] },
  { id: 'dependabot', title: 'Dependabot', aliases: ["dependabot", "Dependabot"] },
  { id: 'codecov', title: 'Codecov', aliases: ["codecov", "Codecov"] },
  { id: 'coveralls', title: 'Coveralls', aliases: ["coveralls", "Coveralls"] },
  { id: 'codacy', title: 'Codacy', aliases: ["codacy", "Codacy"] },
  { id: 'blackduck', title: 'Black Duck', aliases: ["blackduck", "Black Duck", "black duck"] },
  { id: 'veracode', title: 'Veracode', aliases: ["veracode", "Veracode"] },
  { id: 'checkmarx', title: 'Checkmarx', aliases: ["checkmarx", "Checkmarx"] },
  { id: 'semgrep', title: 'Semgrep', aliases: ["semgrep", "Semgrep"] },
  { id: 'trivy', title: 'Trivy', aliases: ["trivy", "Trivy"] },
  { id: 'docker', title: 'Docker', aliases: ["docker", "Docker"] },
  { id: 'dockerhub', title: 'Docker Hub', aliases: ["dockerhub", "Docker Hub", "docker hub"] },
  { id: 'quay', title: 'Quay', aliases: ["quay", "Quay"] },
  { id: 'ghcr', title: 'GitHub Container Registry', aliases: ["ghcr", "GitHub Container Registry"] },
  { id: 'ecr', title: 'Amazon ECR', aliases: ["ecr", "Amazon ECR", "aws ecr"] },
  { id: 'gcr', title: 'Google Container Registry', aliases: ["gcr", "Google Container Registry", "google container registry"] },
  { id: 'acr', title: 'Azure Container Registry', aliases: ["acr", "Azure Container Registry", "azure container registry"] },
  { id: 'kubernetes', title: 'Kubernetes', aliases: ["kubernetes", "Kubernetes", "k8s"] },
  { id: 'helm', title: 'Helm', aliases: ["helm", "Helm"] },
  { id: 'argocd', title: 'Argo CD', aliases: ["argocd", "Argo CD", "argo cd"] },
  { id: 'flux', title: 'FluxCD', aliases: ["flux", "FluxCD", "fluxcd"] },
  { id: 'terraform', title: 'Terraform', aliases: ["terraform", "Terraform"] },
  { id: 'pulumi', title: 'Pulumi', aliases: ["pulumi", "Pulumi"] },
  { id: 'vault', title: 'HashiCorp Vault', aliases: ["vault", "HashiCorp Vault", "hashicorp vault"] },
  { id: 'consul', title: 'Consul', aliases: ["consul", "Consul"] },
  { id: 'nomad', title: 'Nomad', aliases: ["nomad", "Nomad"] },
  { id: 'ansible', title: 'Ansible', aliases: ["ansible", "Ansible"] },
  { id: 'chef', title: 'Chef', aliases: ["chef", "Chef"] },
  { id: 'puppet', title: 'Puppet', aliases: ["puppet", "Puppet"] },
  { id: 'jira', title: 'Jira', aliases: ["jira", "Jira", "atlassian"] },
  { id: 'confluence', title: 'Confluence', aliases: ["confluence", "Confluence"] },
  { id: 'trello', title: 'Trello', aliases: ["trello", "Trello"] },
  { id: 'asana', title: 'Asana', aliases: ["asana", "Asana"] },
  { id: 'linear', title: 'Linear', aliases: ["linear", "Linear"] },
  { id: 'notion', title: 'Notion', aliases: ["notion", "Notion"] },
  { id: 'airtable', title: 'Airtable', aliases: ["airtable", "Airtable"] },
  { id: 'monday', title: 'Monday.com', aliases: ["monday", "Monday.com", "mondaycom"] },
  { id: 'clickup', title: 'ClickUp', aliases: ["clickup", "ClickUp"] },
  { id: 'shortcut', title: 'Shortcut', aliases: ["shortcut", "Shortcut", "clubhouse"] },
  { id: 'height', title: 'Height', aliases: ["height", "Height"] },
  { id: 'basecamp', title: 'Basecamp', aliases: ["basecamp", "Basecamp"] },
  { id: 'zapier', title: 'Zapier', aliases: ["zapier", "Zapier"] },
  { id: 'make', title: 'Make', aliases: ["make", "Make", "integromat"] },
  { id: 'ifttt', title: 'IFTTT', aliases: ["ifttt", "IFTTT"] },
  { id: 'n8n', title: 'n8n', aliases: ["n8n"] },
  { id: 'segment', title: 'Segment', aliases: ["segment", "Segment"] },
  { id: 'mixpanel', title: 'Mixpanel', aliases: ["mixpanel", "Mixpanel"] },
  { id: 'amplitude', title: 'Amplitude', aliases: ["amplitude", "Amplitude"] },
  { id: 'heap', title: 'Heap', aliases: ["heap", "Heap"] },
  { id: 'posthog', title: 'PostHog', aliases: ["posthog", "PostHog"] },
  { id: 'hotjar', title: 'Hotjar', aliases: ["hotjar", "Hotjar"] },
  { id: 'fullstory', title: 'FullStory', aliases: ["fullstory", "FullStory"] },
  { id: 'launchdarkly', title: 'LaunchDarkly', aliases: ["launchdarkly", "LaunchDarkly", "launch darkly", "ld"] },
  { id: 'split', title: 'Split.io', aliases: ["split", "Split.io", "splitio"] },
  { id: 'optimizely', title: 'Optimizely', aliases: ["optimizely", "Optimizely"] },
  { id: 'flagsmith', title: 'Flagsmith', aliases: ["flagsmith", "Flagsmith"] },
  { id: 'growthbook', title: 'GrowthBook', aliases: ["growthbook", "GrowthBook"] },
  { id: 'customerio', title: 'Customer.io', aliases: ["customerio", "Customer.io", "customer io"] },
  { id: 'intercom', title: 'Intercom', aliases: ["intercom", "Intercom"] },
  { id: 'zendesk', title: 'Zendesk', aliases: ["zendesk", "Zendesk"] },
  { id: 'freshdesk', title: 'Freshdesk', aliases: ["freshdesk", "Freshdesk", "freshworks"] },
  { id: 'helpscout', title: 'Help Scout', aliases: ["helpscout", "Help Scout", "help scout"] },
  { id: 'hubspot', title: 'HubSpot', aliases: ["hubspot", "HubSpot"] },
  { id: 'salesforce', title: 'Salesforce', aliases: ["salesforce", "Salesforce"] },
  { id: 'pipedrive', title: 'Pipedrive', aliases: ["pipedrive", "Pipedrive"] },
  { id: 'zoho', title: 'Zoho', aliases: ["zoho", "Zoho"] },
  { id: 'close', title: 'Close CRM', aliases: ["close", "Close CRM", "closecrm"] },
  { id: 'calendly', title: 'Calendly', aliases: ["calendly", "Calendly"] },
  { id: 'calcom', title: 'Cal.com', aliases: ["calcom", "Cal.com", "cal.com"] },
  { id: 'zoom', title: 'Zoom', aliases: ["zoom", "Zoom"] },
  { id: 'googlemeet', title: 'Google Meet', aliases: ["googlemeet", "Google Meet", "google meet", "meet"] },
  { id: 'webex', title: 'Webex', aliases: ["webex", "Webex"] },
  { id: 'gong', title: 'Gong', aliases: ["gong", "Gong"] },
  { id: 'loom', title: 'Loom', aliases: ["loom", "Loom"] },
  { id: 'docusign', title: 'DocuSign', aliases: ["docusign", "DocuSign", "docu sign"] },
  { id: 'dropbox', title: 'Dropbox', aliases: ["dropbox", "Dropbox"] },
  { id: 'box', title: 'Box', aliases: ["box", "Box"] },
  { id: 'googledrive', title: 'Google Drive', aliases: ["googledrive", "Google Drive", "google drive", "gdrive"] },
  { id: 'onedrive', title: 'OneDrive', aliases: ["onedrive", "OneDrive", "one drive"] },
  { id: 'sharepoint', title: 'SharePoint', aliases: ["sharepoint", "SharePoint"] },
  { id: 'figma', title: 'Figma', aliases: ["figma", "Figma"] },
  { id: 'miro', title: 'Miro', aliases: ["miro", "Miro"] },
  { id: 'canva', title: 'Canva', aliases: ["canva", "Canva"] },
  { id: 'adobe', title: 'Adobe', aliases: ["adobe", "Adobe"] },
  { id: 'shopify', title: 'Shopify', aliases: ["shopify", "Shopify"] },
  { id: 'woocommerce', title: 'WooCommerce', aliases: ["woocommerce", "WooCommerce", "woo commerce"] },
  { id: 'bigcommerce', title: 'BigCommerce', aliases: ["bigcommerce", "BigCommerce"] },
  { id: 'magento', title: 'Magento', aliases: ["magento", "Magento", "adobe commerce"] },
  { id: 'prestashop', title: 'PrestaShop', aliases: ["prestashop", "PrestaShop"] },
  { id: 'etsy', title: 'Etsy', aliases: ["etsy", "Etsy"] },
  { id: 'ebay', title: 'eBay', aliases: ["ebay", "eBay"] },
  { id: 'amazon', title: 'Amazon', aliases: ["amazon", "Amazon", "amazon marketplace"] },
  { id: 'openstreetmap', title: 'OpenStreetMap', aliases: ["openstreetmap", "OpenStreetMap", "osm"] },
  { id: 'mapbox', title: 'Mapbox', aliases: ["mapbox", "Mapbox"] },
  { id: 'here', title: 'HERE Maps', aliases: ["here", "HERE Maps", "here maps"] },
  { id: 'tomtom', title: 'TomTom', aliases: ["tomtom", "TomTom"] },
  { id: 'googlemaps', title: 'Google Maps', aliases: ["googlemaps", "Google Maps", "google maps", "gmaps"] },
  { id: 'geocodio', title: 'Geocodio', aliases: ["geocodio", "Geocodio"] },
  { id: 'ipinfo', title: 'IPinfo', aliases: ["ipinfo", "IPinfo"] },
  { id: 'ipstack', title: 'ipstack', aliases: ["ipstack"] },
  { id: 'ipgeolocation', title: 'IP Geolocation', aliases: ["ipgeolocation", "IP Geolocation"] },
  { id: 'maxmind', title: 'MaxMind', aliases: ["maxmind", "MaxMind"] },
  { id: 'recaptcha', title: 'reCAPTCHA', aliases: ["recaptcha", "reCAPTCHA", "google recaptcha"] },
  { id: 'hcaptcha', title: 'hCaptcha', aliases: ["hcaptcha", "hCaptcha"] },
  { id: 'turnstile', title: 'Cloudflare Turnstile', aliases: ["turnstile", "Cloudflare Turnstile", "cloudflare turnstile"] },
  { id: 'twocaptcha', title: '2Captcha', aliases: ["twocaptcha", "2Captcha", "2captcha"] },
  { id: 'zerobounce', title: 'ZeroBounce', aliases: ["zerobounce", "ZeroBounce"] },
  { id: 'neverbounce', title: 'NeverBounce', aliases: ["neverbounce", "NeverBounce"] },
  { id: 'clearbit', title: 'Clearbit', aliases: ["clearbit", "Clearbit"] },
  { id: 'hunter', title: 'Hunter.io', aliases: ["hunter", "Hunter.io", "hunterio"] },
  { id: 'apollo', title: 'Apollo', aliases: ["apollo", "Apollo", "apolloio"] },
  { id: 'serper', title: 'Serper', aliases: ["serper", "Serper"] },
  { id: 'serpapi', title: 'SerpApi', aliases: ["serpapi", "SerpApi", "serp api"] },
  { id: 'bing', title: 'Bing Search', aliases: ["bing", "Bing Search", "bing search"] },
  { id: 'brave', title: 'Brave Search', aliases: ["brave", "Brave Search", "brave search"] },
  { id: 'tavily', title: 'Tavily', aliases: ["tavily", "Tavily"] },
  { id: 'exa', title: 'Exa', aliases: ["exa", "Exa", "exa ai"] },
  { id: 'rapidapi', title: 'RapidAPI', aliases: ["rapidapi", "RapidAPI", "rapid api"] },
  { id: 'apify', title: 'Apify', aliases: ["apify", "Apify"] },
  { id: 'browserless', title: 'Browserless', aliases: ["browserless", "Browserless"] },
  { id: 'scrapeops', title: 'ScrapeOps', aliases: ["scrapeops", "ScrapeOps"] },
  { id: 'scrapfly', title: 'Scrapfly', aliases: ["scrapfly", "Scrapfly"] },
  { id: 'brightdata', title: 'Bright Data', aliases: ["brightdata", "Bright Data", "bright data", "luminati"] },
  { id: 'zyte', title: 'Zyte', aliases: ["zyte", "Zyte", "scrapinghub"] },
  { id: 'oxylabs', title: 'Oxylabs', aliases: ["oxylabs", "Oxylabs"] },
  { id: 'smartproxy', title: 'Smartproxy', aliases: ["smartproxy", "Smartproxy"] },
  { id: 'browserbase', title: 'Browserbase', aliases: ["browserbase", "Browserbase"] },
  { id: 'browserstack', title: 'BrowserStack', aliases: ["browserstack", "BrowserStack"] },
  { id: 'saucelabs', title: 'Sauce Labs', aliases: ["saucelabs", "Sauce Labs", "sauce labs"] },
  { id: 'lambdatest', title: 'LambdaTest', aliases: ["lambdatest", "LambdaTest", "lambda test"] },
  { id: 'mailosaur', title: 'Mailosaur', aliases: ["mailosaur", "Mailosaur"] },
  { id: 'mailtrap', title: 'Mailtrap', aliases: ["mailtrap", "Mailtrap"] },
  { id: 'testmail', title: 'Testmail.app', aliases: ["testmail", "Testmail.app", "testmailapp"] },
  { id: 'onesignal', title: 'OneSignal', aliases: ["onesignal", "OneSignal", "one signal"] },
  { id: 'expo', title: 'Expo', aliases: ["expo", "Expo"] },
  { id: 'pusher', title: 'Pusher', aliases: ["pusher", "Pusher"] },
  { id: 'ably', title: 'Ably', aliases: ["ably", "Ably"] },
  { id: 'pubnub', title: 'PubNub', aliases: ["pubnub", "PubNub"] },
  { id: 'stream', title: 'Stream', aliases: ["stream", "Stream", "getstream"] },
  { id: 'agora', title: 'Agora', aliases: ["agora", "Agora"] },
  { id: 'mux', title: 'Mux', aliases: ["mux", "Mux"] },
  { id: 'bunny', title: 'Bunny.net', aliases: ["bunny", "Bunny.net", "bunnynet", "bunnycdn"] },
  { id: 'fastly', title: 'Fastly', aliases: ["fastly", "Fastly"] },
  { id: 'cloudfront', title: 'CloudFront', aliases: ["cloudfront", "CloudFront", "aws cloudfront"] },
  { id: 'keycdn', title: 'KeyCDN', aliases: ["keycdn", "KeyCDN"] },
  { id: 'cdn77', title: 'CDN77', aliases: ["cdn77", "CDN77"] },
  { id: 'revenuecat', title: 'RevenueCat', aliases: ["revenuecat", "RevenueCat"] },
  { id: 'admob', title: 'AdMob', aliases: ["admob", "AdMob"] },
  { id: 'appmetrica', title: 'AppMetrica', aliases: ["appmetrica", "AppMetrica"] },
  { id: 'auth0', title: 'Auth0', aliases: ["auth0", "Auth0"] },
  { id: 'okta', title: 'Okta', aliases: ["okta", "Okta"] },
  { id: 'onelogin', title: 'OneLogin', aliases: ["onelogin", "OneLogin", "one login"] },
  { id: 'clerk', title: 'Clerk', aliases: ["clerk", "Clerk"] },
  { id: 'stytch', title: 'Stytch', aliases: ["stytch", "Stytch"] },
  { id: 'workos', title: 'WorkOS', aliases: ["workos", "WorkOS", "work os"] },
  { id: 'descope', title: 'Descope', aliases: ["descope", "Descope"] },
  { id: 'fusionauth', title: 'FusionAuth', aliases: ["fusionauth", "FusionAuth"] },
  { id: 'keycloak', title: 'Keycloak', aliases: ["keycloak", "Keycloak"] },
  { id: 'onepassword', title: '1Password', aliases: ["onepassword", "1Password", "1password", "op"] },
  { id: 'doppler', title: 'Doppler', aliases: ["doppler", "Doppler"] },
  { id: 'infisical', title: 'Infisical', aliases: ["infisical", "Infisical"] },
  { id: 'akeyless', title: 'Akeyless', aliases: ["akeyless", "Akeyless"] },
  { id: 'bitwarden', title: 'Bitwarden', aliases: ["bitwarden", "Bitwarden"] },
  { id: 'lastpass', title: 'LastPass', aliases: ["lastpass", "LastPass"] },
  { id: 'dashlane', title: 'Dashlane', aliases: ["dashlane", "Dashlane"] },
  { id: 'duo', title: 'Duo Security', aliases: ["duo", "Duo Security", "duosecurity"] },
  { id: 'rsa', title: 'RSA SecurID', aliases: ["rsa", "RSA SecurID", "securid"] },

];

function normalize(s) {
  return String(s || '').toLowerCase().replace(/[^a-z0-9]+/g, '');
}

function tokens(s) {
  return new Set(String(s || '').toLowerCase().split(/[^a-z0-9]+/).filter(Boolean));
}

const PROVIDER_FINGERPRINTS = [];
const seen = new Set();
for (const provider of PROVIDERS) {
  for (const alias of provider.aliases || []) {
    const norm = normalize(alias);
    if (!norm) continue;
    if (norm.length < 4 && !ALLOWED_SHORT_ALIASES.has(norm)) continue;
    const key = `${provider.id}:${norm}`;
    if (!seen.has(key)) {
      seen.add(key);
      PROVIDER_FINGERPRINTS.push({ provider, norm, raw: alias, withSuffix: false });
    }
    for (const suffix of SECRET_SUFFIXES) {
      const suffixed = normalize(`${alias}_${suffix}`);
      const skey = `${provider.id}:${suffixed}`;
      if (!seen.has(skey)) {
        seen.add(skey);
        PROVIDER_FINGERPRINTS.push({ provider, norm: suffixed, raw: `${alias}_${suffix}`, withSuffix: true });
      }
    }
  }
}

function findProvider(context) {
  const original = String(context || '');
  const compact = normalize(original);
  const tokenSet = tokens(original);
  let fallback = null;

  for (const fp of PROVIDER_FINGERPRINTS) {
    if (!fp.norm) continue;
    // Suffixed fingerprints are high precision, e.g. CLOUDFLARE_API_TOKEN.
    if (fp.withSuffix && compact.includes(fp.norm)) return fp.provider;

    // Short aliases must be exact tokens to avoid matches inside normal words.
    if (fp.norm.length < 5) {
      if (tokenSet.has(fp.norm)) fallback = fallback || fp.provider;
      continue;
    }

    if (compact.includes(fp.norm)) fallback = fallback || fp.provider;
  }
  return fallback;
}

function providerStats() {
  return {
    providers: PROVIDERS.length,
    fingerprints: PROVIDER_FINGERPRINTS.length,
    secretSuffixes: SECRET_SUFFIXES.length
  };
}

module.exports = { PROVIDERS, PROVIDER_FINGERPRINTS, SECRET_SUFFIXES, findProvider, providerStats };
